image:
    name: ubuntu:xenial

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - bin/ci.branches
  branches:
    master:
      - step:
          script:
            - bin/ci
